config/routes.rb
Rails.application.routes.draw do

  resources :places
  resources :reviews

  devise_for :users, controllers: { registrations: "registrations"}

  root 'pages#home'

end

app/models/place.rb
class Place < ActiveRecord::Base
	validates_presence_of :name
	validates_presence_of :phone
	validates_presence_of :website
	validates_presence_of :user_id
	belongs_to :user
	
	geocoded_by :address   
	after_validation :geocode     
	has_many :reviews, dependent: :destroy    
end

app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :user
	belongs_to :place
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_presence_of :name   
  has_many :places, dependent: :destroy   
  has_many :reviews, dependent: :destroy   
end	

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :create, :update, :destroy]
  before_action :set_place, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @places = Place.all
    respond_with(@places)
  end

  def show
    @reviews = @place.reviews
    @review = Review.new
  end

  def new
    @place = Place.new
    respond_with(@place)
  end

  def edit
  end

  def create
    @place = current_user.places.new(place_params)

    respond_to do |format|
      if @place.save
        format.html { redirect_to @place, notice: 'Place was successfully created.' }
        format.json { render :show, status: :created, location: @place }
      else
        format.html { render :new }
        format.json { render json: @place.errors, status: :unprocessable_entity }  
      end
    end
  end

  def update

    respond_to do |format|
      if @place.update(place_params)
        format.html { redirect_to @place, notice: 'Place was successfully updated.' }
        format.json { render :show, status: :ok, location: @place }
      else
        format.html { render :edit }
        format.json { render json: @place.errors, status: :unprocessable_entity }  
      end
    end
  end

  def destroy
    @place.destroy
    respond_to do |format|
        format.html { redirect_to places_url, notice: 'Place was successfully destroyed.' }
        format.json { head :no_content }
    end  
  end


  private
    def set_place
      @place = Place.find(params[:id])
    end

    def place_params
      params.require(:place).permit(:name, :address, :description, :phone, :website)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

	private

	def sign_up_params
		params.require(:user).permit(:name, :email, :password)
		
	end

	def account_update_params
		params.require(:user).permit(:name, :email, :password, :current_password)
	end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
	before_action :authenticate_user!
	before_action :set_review, only: [:edit, :update, :destroy]

  def edit
  end

  def create
  	@review = current_user.reviews.new(review_params)

  	respond_to do |format|
  		if @review.save
  			format.html { redirect_to place_path(@review.place), notice: 'Review was successfully created.' }
  		else
  			redirect_to place_path(@review.place), notice: "Something went wrong!"
  		end
  	end
  end

  def update
  	respond_to do |format|
  		if @review.update(review_params)
  			format.html { redirect_to place_path(@review.place), notice: 'Review was successfully updated.' }
  		else
  			format.html { render :edit }
  			redirect_to place_path(@review.place), notice: "Something went wrong!"	      
  		end
  	end
  end

  def destroy
  	@review.destroy
  	respond_to do |format|
  		format.html { redirect_to place_path(@review.place), notice: 'Review was successfully destroyed.' }
  	end  
  end


  private

  def set_review
  	@review = Review.find(params[:id])
    end

  def review_params
  	params.require(:review).permit(:content, :place_id)
  end  

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button data-target="#bs-example-navbar-collapse-1" data-toggle="collapse" class="navbar-toggle collapsed" type="button">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "StukPlaces", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div id="bs-example-navbar-collapse-1" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        
      <li><%= link_to "Places", places_path %></li>
        
      </ul>
      <form role="search" class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" placeholder="Search" class="form-control">
        </div>
        <button class="btn btn-default" type="submit">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">

        <% if current_user %>

        <li><%= link_to "Settings", edit_user_registration_path %></li>
        <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>

        <% else %>
        <li><%= link_to "Login",  new_user_session_path %></li>
        <li><%= link_to "Signup",  new_user_registration_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Stukplaces</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

<script type="text/javascript"
      src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBcui8nG-SBGzEKHLUSAso3Lnys9p02MtM">
    </script>


</head>
<body>
<%= render "layouts/header" %>

<% flash.each do |type, message| %> 
<div class="alert alert-info fade-in">
<button class="close" data-dismiss="alert">x</button>
<%= message %>
</div>	
<% end %>

<div class="container">

<%= yield %>
</div>
</body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/places/_form.html.erb
<%= simple_form_for(@place) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name, required: true %>
    <%= f.input :address, required: true %>
    <%= f.input :description %>
    <%= f.input :phone, required: true %>
    <%= f.input :website, required: true %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/places/edit.html.erb
<h1>Editing place</h1>

<%= render 'form' %>

<%= link_to 'Show', @place %> |
<%= link_to 'Back', places_path %>

app/views/places/index.html.erb
<h1>Listing places</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Phone</th>
      <th>Website</th>
   
    </tr>
  </thead>

  <tbody>
    <% @places.each do |place| %>
      <tr>
        <td><%= place.name %></td>
        <td><%= place.address %></td>
        <td><%= place.phone %></td>
        <td><%= place.website %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if current_user %>
<%= link_to 'New Place', new_place_path %>
<% end %>

app/views/places/new.html.erb
<h1>New place</h1>

<%= render 'form' %>

<%= link_to 'Back', places_path %>

app/views/places/show.html.erb
<div class="row">

<div class="col-md-3">
<h3><%= @place.name %></h3>
<p>
<strong>Address</strong>
<%= @place.address %>
</p>

<p>
<strong>Phone</strong>

<%= @place.phone %>

</p>

<p>
<strong>Website</strong>

<%= @place.website %>

</p>

<p>
<strong>Description</strong>

<%= @place.description %>

</p> 

<div id="map-canvas" style="width: 230px; height: 230px"></div>


</div>

<div class="col-md-9">

<h3>Reviews by People</h3>
<% if current_user %>
<h5>New Review</h5>
<%= render "reviews/form" %>
<h5>All Reviews</h5>
<%= render @reviews %>

<% end %>
</div>

</div>

<div id="map-canvas" style="width: 230px; height: 230px"></div>

<script type="text/javascript">
      function initialize() {
        var myCenter = {lat: <%= @place.latitude %>, lng: <%= @place.longitude %>}
        var mapOptions = {
          center: myCenter,
          zoom: 8
        };
        var map = new google.maps.Map(document.getElementById('map-canvas'),
            mapOptions);
        var marker = new google.maps.Marker({
          position: myCenter,
          map: map
        });
      }
      google.maps.event.addDomListener(window, 'load', initialize);
    </script>

app/views/reviews/_form.html.erb
<%= simple_form_for(@review) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :content, required: true %>
    <%= f.hidden_field :place_id, required: true, value: @place.id %>

  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/reviews/_review.html.erb
<p><%= gravatar_tag review.user.email, size: 20 %> <%= review.content %> by <%= review.user.name %>